"""Pitch and Categories Migration

Revision ID: 879fc7d0e4dd
Revises: 310da07d5514
Create Date: 2021-09-27 05:01:51.782239

"""

# revision identifiers, used by Alembic.
revision = '879fc7d0e4dd'
down_revision = '310da07d5514'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pitch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pitch_title', sa.String(length=255), nullable=True),
    sa.Column('pitch_content', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pitch')
    op.drop_table('category')
    # ### end Alembic commands ###
