"""Relationship between pitch and user

Revision ID: 9c7673bd5f15
Revises: 879fc7d0e4dd
Create Date: 2021-09-28 01:05:27.245834

"""

# revision identifiers, used by Alembic.
revision = '9c7673bd5f15'
down_revision = '879fc7d0e4dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('pitch_author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitch', 'users', ['pitch_author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.drop_column('pitch', 'pitch_author')
    # ### end Alembic commands ###
