"""Relationship between pitch and vote

Revision ID: fcbf7c028b7e
Revises: 9c7673bd5f15
Create Date: 2021-09-28 02:06:45.617104

"""

# revision identifiers, used by Alembic.
revision = 'fcbf7c028b7e'
down_revision = '9c7673bd5f15'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upvote', sa.String(length=255), nullable=True),
    sa.Column('downvote', sa.String(length=255), nullable=True),
    sa.Column('pitch', sa.Integer(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pitch'], ['pitch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pitch', sa.Column('pitch_author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitch', 'users', ['pitch_author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.drop_column('pitch', 'pitch_author')
    op.drop_table('vote')
    # ### end Alembic commands ###
